// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alive: typeof import('./src/components/Alive/index.vue')['default']
    Bg: typeof import('./src/components/Bg.vue')['default']
    CItem: typeof import('./src/components/cItem.vue')['default']
    Code: typeof import('./src/components/Code.vue')['default']
    CodePen: typeof import('./src/components/CodePen/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Final: typeof import('./src/components/Final/index.vue')['default']
    Item: typeof import('./src/components/Item/index.vue')['default']
    Living: typeof import('./src/components/Living/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Mkdown: typeof import('./src/components/Mkdown/index.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalkTitle: typeof import('./src/components/TalkTitle/index.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    Twinkle: typeof import('./src/components/Twinkle/index.vue')['default']
  }
}
